agent_name = "outrival-agent"
image = "ghcr.io/jchaffin/outrival-agents:latest"
image_credentials = "ghcr-credentials"
secret_set = "outrival-secrets"
agent_profile = "agent-1x"
region = "us-west"

[scaling]
min_agents = 0
